---
title: "MapsUAA"
author: "Kanika Khanna"
date: "`r Sys.Date()`"
output: html_document
---


```{r}
#Install packages
install.packages("acs")
install.packages("tigris")
install.packages("leaflet")
install.packages("mapview")
install.packages("stringr")
install.packages("tidyverse")
install.packages("sp")
install.packages("tmap")
install.packages("maptools")
install.packages("sf")
install.packages("raster")
install.packages("dplyr")

#load libraries
library(acs)
library(tigris)
library(leaflet)
library(mapview)
library(stringr)
library(tidyverse)
library(sp)
library(tmap)
library(tmaptools)
library(sf)
library(dplyr)
library(raster)
options(tigris_use_cache = TRUE)

```

```{r}
shapename <- read_sf('../nyct2010_22b/nyct2010.shp')

```


```{r}
leaflet() %>%
  addTiles() %>%
  setView(-74.00, 40.71, zoom = 12) %>%
  addProviderTiles("CartoDB.Positron")

nyc_tracts <- tracts(state = "NY",  county = c('061','047','081','005','085'), cb = TRUE, 
                        class = "sp")
```

```{r}
#The tigris package makes it easy to grab Census shapefiles at various levels, from tracts and zipcodes all the way up to national borders. First we look up the appropriate codes.
lookup_code("New York", "New York")
lookup_code("New York", "Kings")
lookup_code("New York", "Queens")
lookup_code("New York", "Bronx")
lookup_code("New York", "Richmond")

class(nyc_tracts)

plot(nyc_tracts)
head(nyc_tracts)
```

```{r}
# Then we download the data and take a look at it. The summary below shows the data associated with each polygon (e.g., the GEOID and  NAME). We can access data columns via nyc_tracts@data.
nyc_tracts <- tracts(state = '36', county = c('061','047','081','005','085'))
summary(nyc_tracts)
```

```{r}
plot(nyc_tracts)
```

```{r}
#bringing in my own data
housing_data <- read.csv("TTCDATA.csv")
housing_data$TractPoverty <- as.numeric(housing_data$TractPoverty)
housing_data$pct.pov <- as.numeric(housing_data$pct.pov)
housing_data$GEOID <- as.character(housing_data$GEOID)

glimpse(housing_data)

#mutate percentage variables
housing_data_clean <- housing_data

summary(housing_data_clean)
```
```{r}
#merging!
mydatamerged <- geo_join(nyc_tracts, housing_data_clean, "GEOID", "GEOID", how = 'inner')
summary(mydatamerged)
qtm(shapename)

#nycmaps <- left_join(shapename,housing_data_clean,by="GEOID")

#View(nycmaps)



```

```{r}
#rename the df
nyc_housingtracts <- mydatamerged
```

```{r}
#mapping poverty
mypopup_pov <- paste0("GEOID: ", nyc_housingtracts$GEOID, "<br>", "Poverty Rate: ", round(nyc_housingtracts$pct.pov,0))

#colors
mypal_pov <- colorNumeric(
  palette = "YlGnBu",
  domain = nyc_housingtracts$pct.pov
)

#leaflet
povmap<-leaflet() %>%
  addProviderTiles("CartoDB.Positron") %>%
  addPolygons(data = nyc_housingtracts, 
              fillColor = ~mypal_pov(pct.pov), 
              color = "#b2aeae", # you need to use hex colors
              fillOpacity = 0.7, 
              weight = 1, 
              smoothFactor = 0.2,
              popup = mypopup_pov) %>%
  addLegend(pal = mypal_pov, 
            values = nyc_housingtracts$pct.pov, 
            position = "bottomright", 
            title = "Percent Poverty",
            labFormat = labelFormat(suffix = "%"))

povmap

```
#Here is where I'm running into the trouble with the legend -- it's hard to tell the variance between tracts with no units at all and tracts with say, 150 units. 

```{r}
#mapping units
mypopup_units <- paste0("GEOID: ", nyc_housingtracts$GEOID, "<br>", "Total Income Restricted Units ", round(nyc_housingtracts$LIUnits,0))

#colors
mypal_units <- colorNumeric(
  palette = "YlGnBu",
  domain = nyc_housingtracts$TotalUnits
)

#leaflet
unitmap<-leaflet() %>%
  addProviderTiles("CartoDB.Positron") %>%
  addPolygons(data = nyc_housingtracts, 
             fillColor = ~mypal_units(LIUnits), 
             color = "#b2aeae", # you need to use hex colors
             fillOpacity = 0.7, 
             weight = 1, 
             smoothFactor = 0.2,
             popup = mypopup_units) %>%
  addLegend(pal = mypal_units, 
           values = nyc_housingtracts$LIUnits, 
           position = "bottomright", 
           bins = 7, 
           title = "Income Restricted Units",
           labFormat = labelFormat(suffix = " units"))


unitmap

```
